language: java
sudo: false
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: hsyIdky6EoCW/tUDbJuX6wvo5XXSDml1SQRNHrCGIDgiA6+lkZAzhQPzWgXWclwIQ+u4jf7RrF6Pyun78NPCOpPIfloClhmL1LU36D/dsbgpmFHS+98aelfHh+9M2rEy3hVx3dc+WqjqGk3XXDywyivdPsP2M9uBMD1FnblnO+4=
  # SONATYPE_PASSWORD
  - secure: QXY+UGzkHxAKejekMw6i69XATGlMQhBBzLyCFVN5vdzVk85fqv9osD8yldJeihFeU7TxCJLkXOuotcgAVJmnvWAnElQA9cPXtvFa5C4/+N4BEJHqKpc+dSZ2Nvshq22Yfk460p1JPh/2p7789boa+033WJbT6bQQPU6N5HtpEwA=
  # GPG_PASSPHRASE
  - secure: dk8UptF5LGNLjpJxjqz//fbLqWgQTOmGFWQ/9j5yASCa2V3TAr++ckI8Iin23rogj1lcKcRIn/0j/vafisO6t/jfXeh1fVRhuAO8dwVIWfLAd+S2i/kFz5GPQkt8DAixKfi5DKSPNGAJFcG5D08luq8JZ3qvDg7nCVOgXH5ao8I=
  # GPG_KEYID
  - GPG_KEYID: 0DD20E21
  # GPG_KEY
  - secure: OWNBi3kBddmFANHe3ss79TaVAqi7l/kUXLf4tt5czBL96Aocfp0Pi4cgWwf302kysGhrn6nbhhFYf6iUjPp9xgDZe6KV9s2ncmFX3AbaHPhk7CscNBWnbVYS4p3YsGl5rixbgYxnXpXQVcIhCEz+fokYwX1XV5EAE5BNT+XhH/0=
